/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DotsLoader: typeof import('./src/components/common/DotsLoader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconRefreshRight: typeof import('@element-plus/icons-vue')['RefreshRight']
    LiveVideo: typeof import('./src/components/LiveVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sensors: typeof import('./src/components/Sensors.vue')['default']
    Spinner: typeof import('./src/components/common/Spinner.vue')['default']
    VerticalBarSensor: typeof import('./src/components/sensors/VerticalBarSensor.vue')['default']
  }
}
