/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LiveVideo: typeof import('./src/components/LiveVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sensors: typeof import('./src/components/Sensors.vue')['default']
    VerticalBarSensor: typeof import('./src/components/sensors/VerticalBarSensor.vue')['default']
  }
}
